### ISSUE TITLE
'dx serve' doesnt work

### ISSUE THREAD

**Issue by TBS1996** [Strosel/treman#17]
I'm probably missing something as I'm new to dixous. I'm just trying to figure out how to make my dioxus app into a PWA so I stumbled upon yours. I did 'nix develop' then 'dx serve' but the page is isnt loading the images. Is there something else I should be doing?

**Comment by Strosel** [comment]
Due to how nix works if the directory is tracked by git nix only looks at files that are themselves tracked so you'll have to add them. `git add` is enough for nix to care so no need to commit incomplete work.
